name: Build MariaDB 10.3.33 (Windows x86 Release)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install strawberryperl -y
          choco install python -y

      - name: Configure CMake (Release x86)
        shell: cmd
        run: |
          cmake -S mariadb-10.3.33 -B build ^
            -G "Visual Studio 17 2022" ^
            -A Win32 ^
            -DWITH_SSL=bundled ^
            -DWITH_ZLIB=bundled ^
            -DWITHOUT_TOKUDB=1 ^
            -DWITHOUT_MROONGA=1 ^
            -DWITHOUT_ROCKSDB=1 ^
            -DWITH_UNIT_TESTS=0

      - name: Build (Release)
        shell: cmd
        run: cmake --build build --config Release --parallel

      - name: Package artifacts
        shell: cmd
        run: |
          mkdir package
          copy build\sql\Release\mysqld.exe package\
          copy build\libmariadb\Release\libmariadb.dll package\
          xcopy /E /I include package\include
          xcopy /E /I lib package\lib

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-10.3.33-win32-release
          path: package
