name: Build MariaDB 10.3.33 (Windows Release)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 720

    steps:
      - name: Checkout MariaDB source
        run: |
          git clone --branch mariadb-10.3.33 --depth 1 https://github.com/MariaDB/server.git mariadb
          cd mariadb
          git submodule update --init --recursive

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          choco install cmake --version=3.20.0 -y --allow-downgrade
          choco install ninja winflexbison3 -y
          choco install boost-msvc-14.3 -y

      - name: Patch binary_function for MSVC
        shell: pwsh
        run: |
          # 创建兼容头文件，只在缺失时定义
          Set-Content mariadb/include/my_stl_compat.h '#pragma once'
          Add-Content mariadb/include/my_stl_compat.h '#include <functional>'
          Add-Content mariadb/include/my_stl_compat.h '#ifndef HAS_BINARY_FUNCTION'
          Add-Content mariadb/include/my_stl_compat.h '#if !defined(_HAS_BINARY_FUNCTION) && !defined(_STL_BINARY_FUNCTION_DEFINED)'
          Add-Content mariadb/include/my_stl_compat.h 'namespace std {'
          Add-Content mariadb/include/my_stl_compat.h '  template <class Arg1, class Arg2, class Result>'
          Add-Content mariadb/include/my_stl_compat.h '  struct binary_function {'
          Add-Content mariadb/include/my_stl_compat.h '    typedef Arg1 first_argument_type;'
          Add-Content mariadb/include/my_stl_compat.h '    typedef Arg2 second_argument_type;'
          Add-Content mariadb/include/my_stl_compat.h '    typedef Result result_type;'
          Add-Content mariadb/include/my_stl_compat.h '  };'
          Add-Content mariadb/include/my_stl_compat.h '}'
          Add-Content mariadb/include/my_stl_compat.h '#define HAS_BINARY_FUNCTION'
          Add-Content mariadb/include/my_stl_compat.h '#endif'
          Add-Content mariadb/include/my_stl_compat.h '#endif'

          # 在 ha_innobase.cc 顶部插入 include
          $includeLine = '#include "my_stl_compat.h"'
          $orig = Get-Content mariadb/storage/innobase/handler/ha_innodb.cc
          $new = $includeLine, $orig
          Set-Content mariadb/storage/innobase/handler/ha_innodb.cc $new

      - name: Configure CMake
        run: |
          cd mariadb
          cmake -G "Ninja" . -DCMAKE_BUILD_TYPE=Release -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITHOUT_TOKUDB=1 -DWITHOUT_ROCKSDB=1 -DWITHOUT_OQGRAPH=1 -DWITH_UNIT_TESTS=0 -DWITH_EMBEDDED_SERVER=0 -DCMAKE_INSTALL_PREFIX=install -DBOOST_ROOT="C:/local/boost_1_81_0" -DCMAKE_CXX_STANDARD=14

      - name: Build
        run: |
          cd mariadb
          cmake --build . --config Release

      - name: Install
        run: |
          cd mariadb
          cmake --install . --prefix install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-windows-10.3.33-Release
          path: mariadb/install
