      - name: Patch for MSVC compatibility
        shell: pwsh
        run: |
          # 直接修改有问题的源文件，替换 binary_function 的使用
          $filePath = "mariadb/storage/innobase/handler/ha_innodb.cc"
          $content = Get-Content $filePath -Raw
          
          # 替换所有继承自 std::binary_function 的用法
          # 使用更现代的方式：手动定义类型
          $content = $content -replace 'struct\s+(\w+)\s*:\s*public\s+std::binary_function<([^>]+)>', 'struct $1 { typedef $2 first_argument_type; typedef $2 second_argument_type; typedef bool result_type;'
          
          Set-Content $filePath $content
