name: Build MariaDB 10.3.33 (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 720
    strategy:
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout MariaDB source
        run: |
          git clone --branch mariadb-10.3.33 --depth 1 https://github.com/MariaDB/server.git mariadb
          cd mariadb
          git submodule update --init --recursive

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          choco install cmake --version=3.20.0 -y --allow-downgrade
          choco install ninja winflexbison3 -y
          choco install boost-msvc-14.3 -y

      - name: Patch binary_function for MSVC
        run: |
          echo "#pragma once" > mariadb/include/my_stl_compat.h
          echo "#include <functional>" >> mariadb/include/my_stl_compat.h
          echo "namespace std {" >> mariadb/include/my_stl_compat.h
          echo "  template <class Arg1, class Arg2, class Result>" >> mariadb/include/my_stl_compat.h
          echo "  struct binary_function {" >> mariadb/include/my_stl_compat.h
          echo "    typedef Arg1 first_argument_type;" >> mariadb/include/my_stl_compat.h
          echo "    typedef Arg2 second_argument_type;" >> mariadb/include/my_stl_compat.h
          echo "    typedef Result result_type;" >> mariadb/include/my_stl_compat.h
          echo "  };" >> mariadb/include/my_stl_compat.h
          echo "}" >> mariadb/include/my_stl_compat.h
          echo "#include \"my_stl_compat.h\"" | cat - mariadb/storage/innobase/handler/ha_innodb.cc > temp && move /Y temp mariadb/storage/innobase/handler/ha_innodb.cc

      - name: Configure CMake
        run: |
          cd mariadb
          cmake -G "Ninja" . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITHOUT_TOKUDB=1 -DWITHOUT_ROCKSDB=1 -DWITHOUT_OQGRAPH=1 -DWITH_UNIT_TESTS=0 -DWITH_EMBEDDED_SERVER=0 -DCMAKE_INSTALL_PREFIX=install -DBOOST_ROOT="C:/local/boost_1_81_0" -DCMAKE_CXX_STANDARD=14

      - name: Build
        run: |
          cd mariadb
          cmake --build . --config ${{ matrix.build_type }}

      - name: Install
        run: |
          cd mariadb
          cmake --install . --prefix install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-windows-10.3.33-${{ matrix.build_type }}
          path: mariadb/install
