name: ds

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  MARIADB_VERSION: "10.3.33"

jobs:
  build-windows-x86:
    name: Build MariaDB ${{ env.MARIADB_VERSION }} for Windows x86
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86]

    steps:
    # 步骤1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 步骤2: 设置MSBuild环境
    - name: Setup MSBuild Environment
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.2022'

    # 步骤3: 安装依赖
    - name: Install build dependencies
      run: |
        choco install cmake -y
        choco install nasm -y
        choco install bison -y

    # 步骤4: 配置MariaDB编译
    - name: Configure MariaDB Build
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A Win32 `
          -DWITH_SSL=system `
          -DCMAKE_BUILD_TYPE=Release

    # 步骤5: 编译MariaDB
    - name: Compile MariaDB
      run: |
        cd build
        msbuild MariaDB.sln /p:Configuration=Release /p:Platform=Win32 /m

    # 步骤6: 上传制品
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mariadb-${{ env.MARIADB_VERSION }}-windows-${{ matrix.arch }}
        path: |
          build/sql/Release/mariadbd.exe
          build/sql/Release/mysql.exe
          build/plugin/*/Release/*.dll
        retention-days: 7
