name: Build MariaDB 10.3.33 (Windows x86)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022   # was windows-2019

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install strawberryperl -y
          choco install python -y

      - name: Configure CMake
        run: |
          cmake -S . -B build ^
            -G "Visual Studio 17 2022" ^
            -A Win32 ^
            -DWITH_SSL=bundled ^
            -DWITH_ZLIB=bundled ^
            -DWITHOUT_TOKUDB=1 ^
            -DWITHOUT_MROONGA=1 ^
            -DWITHOUT_ROCKSDB=1 ^
            -DWITH_UNIT_TESTS=0

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mariadb-10.3.33-win32
          path: build/sql/Release/mysqld.exe

